var searchData=
[
  ['samevalues',['SameValues',['../class_math_library_tests_1_1_difference_test.html#aa2c288d1eabccc67deed1f7bee0a42ba',1,'MathLibraryTests::DifferenceTest']]],
  ['secondexpression',['SecondExpression',['../class_g_u_i_calculator_1_1_view_model_1_1_expressions_1_1_base_1_1_two_expression.html#a2eaf3221befed5301b5515242c60fd71',1,'GUICalculator::ViewModel::Expressions::Base::TwoExpression']]],
  ['setactiveexpression',['SetActiveExpression',['../class_g_u_i_calculator_1_1_view_1_1_caret.html#aafc8ad7f1658e6b341c493dbe5b90813',1,'GUICalculator.View.Caret.SetActiveExpression(ViewModel.Expressions.Base.Expression exp)'],['../class_g_u_i_calculator_1_1_view_1_1_caret.html#a5c3b3ba9b9b7c38d35616b86b1517af5',1,'GUICalculator.View.Caret.SetActiveExpression(ViewModel.Expressions.Base.Expression exp, ExpressionSide desiredExpressionSide)']]],
  ['setpropertyvalue',['SetPropertyValue',['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#ade0f04c0f7b18dd5b170e071d5534d38',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.SetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, object value, System.Globalization.CultureInfo culture)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#ade0f04c0f7b18dd5b170e071d5534d38',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.SetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, object value, System.Globalization.CultureInfo culture)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#ade0f04c0f7b18dd5b170e071d5534d38',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.SetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, object value, System.Globalization.CultureInfo culture)']]],
  ['settings',['Settings',['../class_g_u_i_calculator_1_1_properties_1_1_settings.html',1,'GUICalculator::Properties']]],
  ['settings_2edesigner_2ecs',['Settings.Designer.cs',['../_settings_8_designer_8cs.html',1,'']]],
  ['simplifyargument',['SimplifyArgument',['../class_math_library_1_1_simplify_argument.html',1,'MathLibrary.SimplifyArgument'],['../class_math_library_1_1_simplify_argument.html#a06d047cd18815e8b29a48cbd3c235c90',1,'MathLibrary.SimplifyArgument.SimplifyArgument()']]],
  ['simplifyargument_2ecs',['SimplifyArgument.cs',['../_simplify_argument_8cs.html',1,'']]],
  ['simplifyargumenttest',['SimplifyArgumentTest',['../class_math_library_tests_1_1_simplify_argument_test.html',1,'MathLibraryTests']]],
  ['simplifyargumenttest_2ecs',['SimplifyArgumentTest.cs',['../_simplify_argument_test_8cs.html',1,'']]],
  ['simplifyoftwopi',['SimplifyOfTwoPi',['../class_math_library_1_1_simplify_argument.html#add4de300dc53e4c2d9727281e007260e',1,'MathLibrary::SimplifyArgument']]],
  ['sine',['Sine',['../namespace_g_u_i_calculator_1_1_view_model.html#ab009be6633076790edf9a818ecebe90ea6ca9e2d793f678aba7c1b19526592a46',1,'GUICalculator::ViewModel']]],
  ['sinecommand',['SineCommand',['../class_g_u_i_calculator_1_1_view_model_1_1_main_window_v_m.html#a94e91d0b308e062c72ace1c44154104e',1,'GUICalculator::ViewModel::MainWindowVM']]],
  ['sineexp',['SineExp',['../class_math_library_1_1_sine_exp.html',1,'MathLibrary.SineExp'],['../class_math_library_1_1_sine_exp.html#a2a3ed411b9f550e38383cac116ab7e7f',1,'MathLibrary.SineExp.SineExp()']]],
  ['sineexp_2ecs',['SineExp.cs',['../_sine_exp_8cs.html',1,'']]],
  ['sineexptest',['SineExpTest',['../class_math_library_tests_1_1_sine_exp_test.html',1,'MathLibraryTests']]],
  ['sineexptest_2ecs',['SineExpTest.cs',['../_sine_exp_test_8cs.html',1,'']]],
  ['singleexpression',['SingleExpression',['../class_g_u_i_calculator_1_1_view_model_1_1_expressions_1_1_base_1_1_single_expression.html',1,'GUICalculator.ViewModel.Expressions.Base.SingleExpression'],['../class_g_u_i_calculator_1_1_view_model_1_1_expressions_1_1_base_1_1_single_expression.html#a772a6d3a3b1600a399390b4bb42c2376',1,'GUICalculator.ViewModel.Expressions.Base.SingleExpression.SingleExpression()']]],
  ['singleexpression_2ecs',['SingleExpression.cs',['../_single_expression_8cs.html',1,'']]],
  ['squareroot',['SquareRoot',['../class_g_u_i_calculator_1_1_view_1_1_square_root.html',1,'GUICalculator.View.SquareRoot'],['../class_g_u_i_calculator_1_1_view_1_1_square_root.html#a880449b02b87ebc213b957d847bc9044',1,'GUICalculator.View.SquareRoot.SquareRoot()']]],
  ['squareroot_2ecs',['SquareRoot.cs',['../_square_root_8cs.html',1,'']]],
  ['squarerootcommand',['SquareRootCommand',['../class_g_u_i_calculator_1_1_view_model_1_1_main_window_v_m.html#add5650d858b4c6185405a3175d68df17',1,'GUICalculator::ViewModel::MainWindowVM']]],
  ['standarddeviation',['StandardDeviation',['../class_stand_deviation_1_1_standard_deviation.html',1,'StandDeviation']]],
  ['standarddeviation_2ecs',['StandardDeviation.cs',['../_standard_deviation_8cs.html',1,'']]],
  ['standdeviation',['StandDeviation',['../namespace_stand_deviation.html',1,'']]],
  ['subtractionexp',['SubtractionExp',['../class_math_library_1_1_subtraction_exp.html',1,'MathLibrary.SubtractionExp'],['../class_math_library_1_1_subtraction_exp.html#aeb00ffde12800b77590979d7dc15e85e',1,'MathLibrary.SubtractionExp.SubtractionExp()']]],
  ['subtractionexp_2ecs',['SubtractionExp.cs',['../_subtraction_exp_8cs.html',1,'']]],
  ['subtractionexptest',['SubtractionExpTest',['../class_math_library_tests_1_1_subtraction_exp_test.html',1,'MathLibraryTests']]],
  ['subtractionexptest_2ecs',['SubtractionExpTest.cs',['../_subtraction_exp_test_8cs.html',1,'']]]
];
